### ISSUE TITLE
Cannot run full node

### ISSUE THREAD

**Issue by Aareon** [cranklin/crankycoin#14]
```py
(venv) PS C:\Users\User\crankycoin> py .\run.py full


full node starting...


DEBUG:crankycoin:queue process starting...
DEBUG:crankycoin:worker process(es) starting...
Traceback (most recent call last):
  File ".\run.py", line 218, in <module>
    main(sys.argv[1:])
  File ".\run.py", line 212, in main
    full()
  File ".\run.py", line 119, in full
    full_node.start()
  File "C:\Users\User\crankycoin\crankycoin\node.py", line 79, in start
    wp.start()
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'ConfigDict.__init__.<locals>.<lambda>'
[INFO/MainProcess] process shutting down
[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
[INFO/MainProcess] calling join() for process Process-1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
[INFO/Process-1] child process calling self.run()
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
[INFO/Process-2] process shutting down
[DEBUG/Process-2] running all "atexit" finalizers with priority >= 0
[DEBUG/Process-2] running the remaining "atexit" finalizers
[INFO/Process-1] process shutting down
[DEBUG/Process-1] running all "atexit" finalizers with priority >= 0
[DEBUG/Process-1] running the remaining "atexit" finalizers
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\User\crankycoin\crankycoin\services\queue.py", line 18, in start_queue
    frontend.bind(cls.QUEUE_BIND_IN)
  File "zmq\backend\cython\socket.pyx", line 547, in zmq.backend.cython.socket.Socket.bind
  File "zmq\backend\cython\checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Protocol not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\User\crankycoin\crankycoin\services\queue.py", line 26, in start_queue
    logger.error("could not start queue: %s", e.message)
AttributeError: 'ZMQError' object has no attribute 'message'
[INFO/Process-1] process exiting with exitcode 1
[DEBUG/MainProcess] running the remaining "atexit" finalizers
```

**Comment by Aareon** [comment]
Could possibly have something to do with https://github.com/cranklin/crankycoin/issues/3

**Comment by Aareon** [comment]
Might also have something to do with https://github.com/sailfish-team/sailfish/issues/33

**Comment by Aareon** [comment]
And also possibly related to this https://stackoverflow.com/questions/15386121/does-zeromq-support-ipc-as-a-transport-channel-on-windows

**Comment by Aareon** [comment]
@cranklin im going to try to replicate this on Linux, but I think it's Windows specific

**Comment by Aareon** [comment]
@cranklin what version of Python did you design this in, and on what OS?

**Comment by Aareon** [comment]
In my Py2.7 environment, I get the following exception
```py
pickle.PicklingError: Can't pickle <function <lambda> at 0x0000000004B97F28>: it's not found as bottle.<lambda>```

**Comment by Aareon** [comment]
Is a move to `asyncio` out of the question? If we *were* to move, we could actually remove the requirement for `bottle` and use the builtin asyncio web framework

**Comment by Aareon** [comment]
That and the fact that IPC isn't compatible with Windows at all, this coin is completely unusable on Windows machines

**Comment by meherett** [comment]
Hey @Aareon! for this Error 
### pickle.PicklingError: Can't pickle <function <lambda> at 0x0000000004B97F28>: it's not found as bottle.<lambda>
pip install dill
You can fix it by using ### import dill in run.py

**Comment by cranklin** [comment]
I'm looking into using asyncio's web framework.   I like this idea, but if we rely on asyncio, we're going to have to drop support for Python 2.7 (maybe that's a good idea).  I chose bottle because it's so lightweight and it's great for a thin API layer, but It seems to rely on `Threading`.  I'll test this out in a different branch.

Regarding ZeroMQ, I think this is causing issues here.  I wanted to keep the API layer very thin and have it responsible for a very light validation up front before pushing messages onto a queue.  The consumers would ideally be scaled up/down based on the individual's machine and/or needs (independent of the externally facing API).  ZeroMQ seemed like the ideal solution for interprocess communication without having to spin up a separate queue/broker.  
Thoughts?

**Comment by InfernalPlank** [comment]
@cranklin @Aareon still receiving the errors Aareon first mentioned on Windows-based OSes running Python 3.X; has there been any fix for this? If not, how is the setup for Arch?
